config/routes.rb
Rails.application.routes.draw do
  get  'users/about' => 'users#about',as: 'user_about'
  #patch 'users/:id' => 'users#update', as: 'update_user'
  devise_for :users
  resources :users
  resources :books#, only: [:show, :new, :create, :indexs]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	 belongs_to :user
	 # has_many :books, dependent: :destroy
	 validates :title, presence: true, length: {maximum: 200}
	 validates :body,  presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  validates :name, presence: true, length: {in: 2..20}
  validates :body, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?



    def after_sign_in_path_for(resource) #ログイン後のパス
    	user_path(current_user.id)
  	end

  	def after_sign_out_path_for(resource) #ログアウト後のパス
    	new_user_path
  	end

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 before_action :authenticate_user!
 # before_action :correct_user, only: [:edit, :update]

  def show
    @book = Book.new
    @bookn = Book.find(params[:id])
    @user = @bookn.user
  end

  def index
  	@books = Book.all
    @book = Book.new
    @bookn = User.find(current_user.id)
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
  	if @book.save
      flash[:notice] = "successfully"
  	   redirect_to book_path(@book)
     else
      @user =current_user
      @books = @user.books.all
      render 'users/show'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      redirect_to book_path(@book)
    end
  end

  def update
  @book = Book.find(params[:id])
             if @book.update(book_params)
                flash[:notice] = "successfully"
                redirect_to book_path(@book)
             else
                render 'books/edit'
             end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path

  end


   private
   def book_params
   	params.require(:book).permit(:title,:body)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, except: [:about, :new, :edit]
  def about

  end

  def show
    #@book = Book.find(params[:id])
    @user = User.find(params[:id])
    @books = @user.books.all
    #@book = Book.new

   # @user_images = @user.book_images.page(params[:page]).reverse_order
    @book = Book.new
  end

  def index
    @users = User.all
    # @user = User.new
    @book = Book.new
  	#@books = Book.all
    #book = Book.new

  end

  def new
  	#@book = Book.new
  end

  def create
  	#book = Book.new(book_params)
  	#book.save
  	#redirect_to book_path(book)
  end

  def edit
    #@book = Book.find(params[:id])
    @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
       if @user.update(user_params)
        flash[:notice] = "successfully"
        redirect_to user_path(@user)
       else
        render :edit
       end
  end

  def destroy
    #book = Book.find(params[:id])
    #book.destroy
    #redirect_to books_path(book)

  end


   private
   def book_params
   	params.require(:user).permit(:title, :body, :image)
   end
   def user_params
    params.require(:user).permit(:name, :body, :image)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
 <p id="notice"></p>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
     <h1>Editing Book</h1>
       <% if @book.errors.any? %>
         <div id="error_explanation" class="alert alert-danger">
           <ul>error
             <% @book.errors.full_messages.each do |message| %>
               <li><%= message %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <%= form_for(@book) do |f| %>
        <div class="field row">
         <p><label for="book_title">Title</label></p>
         <p><%= f.text_field :title, class: "col-xs-12 book_title book_title" %></p>
        </div>
        <div class="field row">
         <p><label for="book_opinion">Opinion</label></p>
         <p><%= f.text_area :body, class: "col-xs-12 book_body book_body" %></p>
        </div>
        <div class="actions row">
         <p><%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %></p>
        </div>
       <% end %>
        <%= link_to "show",book_path(@book.id), class: "book_#{@book.id}" %>
        |
        <a class="back" href="/books">Back</a>
    </div>
  </div>
    <footer>
      <div class="container">
　       <div class="col-xs-3 col-xs-offset-9">
　        <p>CopyRight Infratop.inc</p>
         </div>
      </div>
    </footer>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="container">
   <p id="notice"></p>
     <div class="row">
      <%= render 'users/list', user: @bookn %>
       <div class="col-xs-9">
        <h2>Books</h2>
         <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
           </tr>
          </thead>
            <tbody>
             <% @books.each do |book| %>
              <tr>
               <td><span><%= link_to user_path(book.user), class: "user_#{book.id}" do %>
                  <%= attachment_image_tag book.user, :image, :fill, 100, 100, fallback: 'no_image.jpeg', :size => '50x50' %>
                <% end %></span></td>
               <td><span><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></span></td>
               <td><span><%= book.body %></span></td>
              </tr>
             <% end %>
            </tbody>
          </table>
         </div>
       </div>
  </div>
<footer>
<div class="container">
　<div class="col-xs-3 col-xs-offset-9">
　 <p>CopyRight Infratop.inc</p>
</div>
</div>
</footer>

app/views/books/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>
 
    <h4>Title</h4>
    <%= f.text_field :title %>
 

 
    <h4>Opinionr</h4>
    <%= f.text_area :body %>
 
    <%= f.submit '投稿' %>
 
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
  </div>
<% end %>


<div class="container">
  <p id="notice"></p>
    <div class="row">
      <%= render 'users/list', user: @user, book: @book %>
      <div class="col-xs-9">
      <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <thead>
           <tr>
           	 <th></th>
           	 <th></th>
           	 <th></th>
           	 <th></th>
           </tr>
          </thead>
           <tbody>
            <tr>
           	  <td><span>
                <%= link_to user_path(@user), class: "user_#{@user.id}" do %>
                  <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: 'no_image.jpeg', :size => '50x50' %>
                  <%=  content_tag :p ,@user.name %>
                <% end %>
              </span></td>
           	  <td><span><%= link_to @bookn.title, book_path(@bookn.id), class: "book_#{@bookn.id}" %></span></td>
           	  <td><span><%= @bookn.body %></span></td>
              <% if @bookn.user_id == current_user.id %>
           	  <td><%= link_to "edit", edit_book_path(@bookn.id),class: "btn-sm btn-success edit_book_4353 edit_book_#{@bookn.id}" %></td>
              <td><%= link_to "destroy", book_path(@bookn.id), class: "btn-sm btn-danger destroy_book_#{@bookn.id}", method: :delete, "data-confirm" => "本当に消しますか?" %></td>
            </tr>
            <% end %>
           </tbody>
        </table>
<footer>
<div class="container">
　<div class="col-xs-3 col-xs-offset-9">
　 <p>CopyRight Infratop.inc</p>
</div>
</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar  navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left ">
          <span>Bookers</span>
        </nav>
         <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
           <%= link_to " Home",user_path(current_user.id),class: "glyphicon glyphicon-home home" %>
           <%= link_to"Users","/users", class: "glyphicon glyphicon-user users" %>
           <%=link_to "Books","/books",class: "glyphicon glyphicon-book books" %>
           <%= link_to "  logout",destroy_user_session_path,method: :delete,class: "glyphicon glyphicon-log-out logout logout" %>
            <% else %>
           <%= link_to " Home",new_user_path,class: "glyphicon glyphicon-home home" %>
           <%= link_to "  About",user_about_path,class: "glyphicon glyphicon-link about about" %>
           <%= link_to "  Sign Up","/users/sign_up",class: "glyphicon glyphicon-edit sign_up" %>
           <%= link_to "  Login","/users/sign_in",class: "glyphicon glyphicon-log-in sign_in" %>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/_list.html.erb
<% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>error
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
      <div class="col-xs-3">
      <h2>User info</h2>
      <div class="profile-container">
          <%= attachment_image_tag user, :image, :fill, 100, 100, fallback: 'no_image.jpeg' %>

    </div>
      <table class="table">
          <tr></tr>
          <tr>
            <th>name</th><th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th><th><%= user.body %></th>
          </tr>
      </table>
      <div class="row">
        <%= link_to "",edit_user_path(user.id),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_2391 edit_user_#{user.id}" %>
      </div>
      <h2>New book</h2>
      <%= form_for(@book) do |f| %>
        <div class="field row " >  <!--後で変更-->
          <p><%= f.label :title %></p>
          <p><%= f.text_field :title, class: "col-xs-12 book_title " %></p>
        </div>
        <div class="field row">
          <p><%= f.label :Opinion %></p>
          <p><%= f.text_area :body, class: "col-xs-12 book_body" %></p>
        </div>
        <div class="actions row ">
          <p><%= f.submit  'Create Book', :class=>"btn btn-primary col-xs-12" %></p>
        </div>
      <% end %>
    </div>

app/views/users/about.html.erb
<div class="container">
<p id="notice"></p>
<h1>
Welcome to
<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>
!
</h1>
</div>
<footer>
	<div class="container">
	 <div class="row">
	  <p>CopyRight Infratop.inc</p>
	 </div>
	</div>
</footer>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>error
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <%= form_for(@user) do |f| %>
    <div class="field">
      <label for="user_name">Name <%= f.text_field :name, class: "name" %></label>
    </div>
    <div class="field">
      <label for="user_image">Image</label>
      <%= f.attachment_field :image, format: 'jpeg', class: "user_image" %>
    </div>
    <div class="field">
　　 　<label for="user_introduction">Introduction <%= f.text_area :body, class: "introduction" %></label>
    </div>
     <%= f.submit 'Update User' %>
   <% end %>
  </div>
<footer>
<div class="container">
　<div class="col-xs-3 col-xs-offset-9">
　 <p>CopyRight Infratop.inc</p>
</div>
</div>
</footer>

app/views/users/index.html.erb
<div class="container">
　<p id="notice"></p>
　　　<div class="row">
		　　<%= render 'users/list', user: current_user %>
            <div class="col-xs-9">
             <h2>Users</h2>
              <table class="table table-hover table-inverse">
               <thead>
                <tr>
                 <th>image</th>
                 <th>name</th>
                 <th colspan="3"></th>
                </tr>
               </thead>
                <tbody>
                 <% @users.each do |user| %>
                  <tr>
                   <td><span><%= attachment_image_tag user, :image, :fill, 100, 100, fallback: 'no_image.jpeg', :size => '50x50' %></span></td>
                   <td><span><%= user.name %></span></td>
                   <td></td>
                   <td></td>
                   <td></td>
                   <td><%= link_to "show",user_path(user.id), class: "user_#{user.id}" %></td>
                  </tr>
                 <% end %>
                </tbody>
               </table>
            </div>
    </div>
</div>
<footer>
<div class="container">
　<div class="col-xs-3 col-xs-offset-9">
　 <p>CopyRight Infratop.inc</p>
</div>
</div>
</footer>

app/views/users/new.html.erb
<html>
<body>
	<div class ="container">
<div class= "row">
 <div class="top-message col-md-offset-3 col-md-6">

 <h1>welcome to
 <span class="glyphicon glyphicon-book">
 <strong>Bookers</strong>
  !!
 </span>
 </h1>
 <p>In
 <span class="glyphicon glyphicon-book"></span>
 <strong>Bookers</strong>
 ,
</p>
 <p>you can share and exchange your opinions , inpressions , and emotions</p>
 <p>about varioius books!</p>

 <div class="btn-wrapper">
  <div class="row">
   <p>
   <a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a>
   </p>
  </div>
    <div class="row">
    <p>
   <a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a>
    </p>
  </div>
 </div>

</div>
 </div>
    </div>
<footer>
<div class="container">
　<div class="col-xs-3 col-xs-offset-9">
　 <p>CopyRight Infratop.inc</p>
</div>
</div>
</footer>
</body>
</html>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
   <p id="notice"></p>
  <div class="row">
    <%= render 'users/list', user: current_user %>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
      	  <% @books.each do |book| %>
            <tr>
              <td><span><%= link_to user_path(@user), class: "user_#{@user.id}" do %>
                  <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: 'no_image.jpeg', :size => '50x50' %>
                <% end %></span></td>
              <td><span><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></span></td>
              <td><span><%= book.body %></span></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>